"""Regenerate backend/fixtures/simulation.json from a real simulator run.

The fixture is the $800-laptop result the frontend falls back to when the backend
is unreachable, so it has to be something the engine would actually produce. It
used to be maintained by hand, which meant an engine change could silently leave
the offline demo telling a different story from the live one. Run this after any
change that moves the numbers:

    cd backend && uv run python -m backend.regenerate_simulation_fixture

`test_simulation_fixture.py` fails if the committed fixture and a fresh seed-1
run disagree. Then run `sync_frontend_mocks` to push it out to the frontend.
"""

import json
from datetime import date
from pathlib import Path

from backend.fixtures import FIXTURES_DIR, load_twin
from backend.schemas import SimulationEvent, SimulationRequest, SimulationResponse
from backend.simulation import run_simulation

SEED = 1
SIMULATION_ID = "sim_fixture_alex_laptop"
LAPTOP = SimulationEvent(
    type="purchase",
    description="Laptop",
    amount=800.0,
    date=date(2026, 9, 20),
    account_id="acc_checking",
)
PRECOMPUTED_NOTE = (
    f"Precomputed result: generated by the Monte Carlo simulator (seed {SEED}) for this "
    "$800 laptop request; it does not respond to other requests."
)


def build() -> SimulationResponse:
    """The canonical fixture response. Deterministic: same input, same bytes."""
    twin = load_twin()
    # Sent explicitly, the way the frontend does (app/page.tsx posts the goal deadline),
    # so the fixture echoes back the request a real demo would have made.
    request = SimulationRequest(
        user_id="alex", events=[LAPTOP], horizon_end=twin.goals[0].deadline
    )
    response = run_simulation(twin, request, seed=SEED)
    return response.model_copy(
        update={
            "simulation_id": SIMULATION_ID,
            "is_mock": True,
            "assumptions": [PRECOMPUTED_NOTE, *response.assumptions],
        }
    )


def write() -> Path:
    path = FIXTURES_DIR / "simulation.json"
    payload = json.dumps(build().model_dump(mode="json"), indent=2, ensure_ascii=False)
    path.write_text(payload + "\n")
    return path


if __name__ == "__main__":
    print(f"wrote {write()}")
